site_name: KPI monthly report.doc
site_url: 'EDFRS OP Tool doc'
site_author: Gwen ADOLPHE <gwen.adolphe@edf-re.de>

nav: 
  - Home: 'index.md'
  - Project Overview:
    - 'Architecture': 'user_guide/architecture.md'
    - Data How it's work ?: 'user_guide/Data.md'
    - Install environment: 'user_guide/Getting_start.md'
    - Virtual environment: 'user_guide/virtual_env.md'
    - Developer Guide:
      - Add KPI: 'user_guide/dev_guide/add_kpi.md'
      - How to add a project in your report: 'user_guide/dev_guide/add_project.md'
  - Libraries:
    - KPI_lib:
      - Import KPI: 'librairies/kpi_lib/import_kpi.md'
      - Export KPI: 'librairies/kpi_lib/export_kpi.md'
      - HLZ: 'librairies/kpi_lib/hlz.md'
      - KPI:
        - Basic KPI: 'librairies/kpi_lib/kpi_py/basic_kpi_class.md'
        - FCR: 'librairies/kpi_lib/kpi_py/fcr_class.md'
        - KPI fig: 'librairies/kpi_lib/kpi_py/kpi_fig-class.md'
      - Plot KPIs: 'librairies/kpi_lib/kpi_plot.md'
    - PDF_Report_lib:
      - BESS Report: 'librairies/pdf_report_lib/bess_report.md'
    - UI library:
      - UI tools: 'librairies/UI_lib/UI_tools.md'
      - UI for project: 'librairies/UI_lib/UI_project.md'
  - About:
    - Issues:
      - Library Issues: 'About/issues/lib_issues.md'
    - Release Notes: 'About/release_notes.md' 
    - 404: 'none.md'

theme:
  name: material
  custom_dir: custom_theme/
  font:
    text: Arial
  palette: 
    primary: green
  # For logo and icon
  logo: 'image/logo_edf-renewables_WHITE.png'
  favicon: img/favicon.ico


